version: "3.4"
services:
  echo-server:
    container_name: "echo-server"
    build:
      context: .
      target: base
      args:
        PORT: 8888
    command: "air"
    ports:
      - "8888:8888"
    volumes:
      - .:/go/app/base
    depends_on:
      - echo-db
    environment:
      - GO_ENV=${GO_ENV}
      - POSTGRES_URI="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB_NAME}:5432/${POSTGRES_DB}?sslmode=disable"

  echo-db:
    container_name: ${POSTGRES_DB_NAME}
    image: postgres:14
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/echo-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
